# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Piráti Pardubice
email: pardubice@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
keywords: pardubice, piráti, pirátská strana, politická strana, politika, otevřenost, transparentnost
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pardubice.pirati.cz" # the base hostname & protocol for your site

administrator:
  email: xaralis93@gmail.com # mail kam pujdou chybove vystupy

theme: jekyll-theme-pirati

sass:
  style: compressed
  sass_dir: _sass

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-environment-variables
  - jekyll-redirect-from

paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - Dockerfile
  - docker-compose.yml
  - deploy_rsa_sandbox.enc
  - deploy_rsa_sandbox.pub
  - navod.md
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /tiskove-zpravy/:title/
collections:
  people:
    output: true
    root: /clenove/
    permalink: /clenove/:path/

  program:
    output: true
    permalink: /komunalni-volby-2018/program/:path/

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
        - foto
        - personContact
        - people
      keywords: členové, příznivci, lidé
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
        - garant
        - intentionMapLink
        - program
      keywords: program, volby, 2018, komunální volby

organization:
  name: Piráti Pardubice
  shortName: Piráti Pardubice
  email: pavel.stepanek@pirati.cz
  contactUid: jitka.ceskova
  phone: +420 770 113 647
  address: |
    Radoušova 14
    537 01 Chrudim
  residenceImg: miscellaneous/cpice.jpg
  mapLink: https://mapy.cz/zakladni?base=ophoto&q=Radou%C5%A1ova%2014,%20Chrudim
  redmineLink: https://redmine.pirati.cz/projects/pardubicky-kraj
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010
  transparentAccountSpecificSymbol: 190801

contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: organizationPhone
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: custom
    iconClass: fa fa-facebook
    label: Facebooková stránka
    body: <a href="https://www.facebook.com/PiratiPardubice/" target="_blank">Piráti - Pardubice</a>
  - type: custom
    iconClass: fa fa-facebook
    label: Facebooková skupina
    body: <a href="https://www.facebook.com/groups/pirati.pardubice/" target="_blank">Piráti a přátelé Pardubice</a>

calendar:
  # To enable a nicer calendar, make sure you start jekyll with GOOGLE_CALENDAR_APIKEY=[apikey] bundle exec jekyll serve
  title: Nadcházející události
  id: nk73m1m89vhf5g2vojp6tnqe58@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=nk73m1m89vhf5g2vojp6tnqe58%40group.calendar.google.com&ctz=Europe%2FPrague&amp;color=%232952A3

facebook:
  profilePage: https://www.facebook.com/PiratiPardubice/
  groupPage: https://www.facebook.com/groups/pirati.pardubice/
  loadSDK: true
  appId: 1526197851008996

twitter:
  # profile: PiratskaStrana
  loadSDK: true

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

gplus:
  profilePage: https://plus.google.com/u/0/+piratskastrana

forum:
  page: https://forum.pirati.cz/pardubicky-kraj-f85/

github:
  url: https://github.com/pirati-web/pardubice.pirati.cz/
  branch: master

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-6.7.2/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass

